#
# Copyright 2023, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: @ahrenstein
#
# See LICENSE

version: '2'
services:
  cloudflare-mnet-server:
    container_name: cloudflare-mnet-server
    image: ghcr.io/route1337/cloudflare-mnet-server:latest
    environment:
      NETWORK_NAME: Some Network Name
    volumes:
      - ./data/cert:/cert
    ports:
      - "8443:8443"
    restart: always
