name: 'Deploy container to latest tag'

on:
  push:
    branches:
      - main

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          echo "Building container..."
          docker build -f Dockerfile -t ghcr.io/route1337/cloudflare-mnet-server:latest .
          echo "Pushing container to Docker Hub..."
          docker push ghcr.io/route1337/cloudflare-mnet-server:latest
          echo "Done!"
