name: 'Deploy container to named tag'

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract tag name
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the container to GitHub Container Registry using the repo tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/route1337/cloudflare-mnet-server:${{ steps.extract_tag.outputs.tag }}
          push: true
